# Generated by Django 3.0.6 on 2020-05-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.TextField()),
                ('Event_Start_Date', models.DateField()),
                ('Event_Start_Time', models.TimeField()),
            ],
        ),
    ]
