# Generated by Django 3.0.6 on 2020-05-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Event_IconFile',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='Event_MapFile',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
