# Generated by Django 3.0.6 on 2020-05-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='Nazwa_Ewentu',
        ),
    ]
