# Generated by Django 3.0.6 on 2020-05-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200528_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Event_IconFile',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Event_MapFile',
        ),
        migrations.AddField(
            model_name='event',
            name='Event_Description',
            field=models.TextField(default='Opis'),
        ),
        migrations.AddField(
            model_name='event',
            name='Event_Program',
            field=models.TextField(default='Program'),
        ),
    ]
