# Generated by Django 3.0.6 on 2020-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200527_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazawa_Biletu', models.TextField()),
                ('Ilosc_Biletu', models.SmallIntegerField()),
                ('Cena_Biletu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ListaBiletow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dupa', models.TextField()),
            ],
        ),
    ]
