# Generated by Django 3.0.6 on 2020-05-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_bilet_listabiletow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bilet',
            new_name='Ticket',
        ),
        migrations.RenameModel(
            old_name='ListaBiletow',
            new_name='TicketList',
        ),
    ]
