# Generated by Django 3.0.6 on 2020-05-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200529_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallevent',
            name='Main_Event_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.MainEvent'),
        ),
    ]
