# Generated by Django 3.0.6 on 2020-05-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200527_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Nazwa_Ewentu',
            new_name='Event_Name',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Ilosc_Biletu',
            new_name='Ticket_Amount',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Nazawa_Biletu',
            new_name='Ticket_Name',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Cena_Biletu',
            new_name='Ticket_Price',
        ),
    ]
