# Generated by Django 3.0.6 on 2020-05-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200527_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='event2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.TextField()),
                ('Event_date', models.DateTimeField()),
            ],
        ),
    ]
