# Generated by Django 3.0.6 on 2020-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_smallevent_main_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainevent',
            name='Event_End_Date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='Event_Start_Date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='smallevent',
            name='Show_End_Date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='smallevent',
            name='Show_Name',
            field=models.TextField(default='Small event'),
        ),
        migrations.AlterField(
            model_name='smallevent',
            name='Show_Start_Date',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
