# Generated by Django 3.0.6 on 2020-05-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200529_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smallevent',
            old_name='Show_Description',
            new_name='SmallEvent_Description',
        ),
        migrations.RenameField(
            model_name='smallevent',
            old_name='Show_End_Date',
            new_name='SmallEvent_End_Date',
        ),
        migrations.RenameField(
            model_name='smallevent',
            old_name='Show_End_Time',
            new_name='SmallEvent_End_Time',
        ),
        migrations.RenameField(
            model_name='smallevent',
            old_name='Show_Name',
            new_name='SmallEvent_Name',
        ),
        migrations.RenameField(
            model_name='smallevent',
            old_name='Show_Start_Date',
            new_name='SmallEvent_Start_Date',
        ),
        migrations.RenameField(
            model_name='smallevent',
            old_name='Show_Start_Time',
            new_name='SmallEvent_Start_Time',
        ),
    ]
