# Generated by Django 3.0.6 on 2020-05-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event2',
        ),
    ]
