# Generated by Django 3.0.6 on 2020-05-29 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_auto_20200529_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Main_Event_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.MainEvent')),
                ('User_Add', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
