# Generated by Django 3.0.6 on 2020-05-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200529_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallevent',
            name='SmallEvent_Prelegent',
            field=models.TextField(default='Prelegent'),
        ),
    ]
