# Generated by Django 3.0.6 on 2020-05-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200529_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregister',
            name='Main_Event_ID',
        ),
        migrations.AddField(
            model_name='eventregister',
            name='SmallEvent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.SmallEvent'),
        ),
    ]
