# Generated by Django 3.0.6 on 2020-05-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200529_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmallregister',
            name='EventRegister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventRegister'),
        ),
    ]
