# Generated by Django 3.0.6 on 2020-05-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200529_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregister',
            name='User_name',
            field=models.TextField(default='Imie'),
        ),
        migrations.AddField(
            model_name='eventregister',
            name='User_surname',
            field=models.TextField(default='Nazwisko'),
        ),
    ]
