# Generated by Django 3.0.6 on 2020-05-29 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_smallevent_smallevent_prelegent'),
        ('events', '0014_auto_20200529_1428'),
    ]

    operations = [
    ]
