# Generated by Django 3.0.6 on 2020-05-29 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_merge_20200530_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregister',
            name='User_name',
            field=models.TextField(default='Imie'),
        ),
        migrations.AddField(
            model_name='eventregister',
            name='User_surname',
            field=models.TextField(default='Nazwisko'),
        ),
        migrations.CreateModel(
            name='eventOpinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opinion', models.TextField(max_length=250)),
                ('Name', models.TextField(default='User', max_length=100)),
                ('Main_Event_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.MainEvent')),
            ],
        ),
    ]
