# Generated by Django 3.0.6 on 2020-05-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_smallevent_smallevent_prelegent'),
        ('events', '0015_auto_20200529_1603'),
    ]

    operations = [
    ]
