# Generated by Django 3.0.6 on 2020-05-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(max_length=250)),
                ('event_place', models.TextField(max_length=250)),
                ('event_date', models.DateField()),
                ('event_time', models.DateTimeField()),
                ('event_dec', models.TextField(max_length=250)),
            ],
        ),
    ]
