# Generated by Django 3.0.6 on 2020-05-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_mainevent_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainevent',
            name='author',
        ),
    ]
